### ISSUE TITLE
反馈：engage-retain-users/add-to-home-screen/app-install-banners.md

### ISSUE THREAD

**Issue by cgx9** [searchfe/pwa-doc#23]
related_applications的图标google官方文档要求是192x192，而不是144x144.见地址：https://developers.google.com/web/fundamentals/app-install-banners/?hl=en#native_app_install_banners

**Comment by clark-t** [comment]
@cgx9  感谢提醒，已修改。由于 PWA 的标准仍在不断完善，google 的官方文档也在不停变动，我们会定期保持同步哦~
