### ISSUE TITLE
反馈：offline-and-cache-loading/service-worker/how-to-use-service-worker.md

### ISSUE THREAD

**Issue by lazysheep** [searchfe/pwa-doc#24]
隐身窗口这样的名词，不太常用，最好多加解释一下；service worker安装这一块描述了安装步骤，最好讲解一下为什么这么做，有哪些其他api等等。会不明白这些操作都是在干什么，我还能做其他的事情吗。

**Comment by zoumiaojiang** [comment]
谢谢指出问题，已经加上了相应的一些注释，不过想要了解的更加透彻最好还是将文档中的链接都点进去全面了解一下，因为无法将每个知识点都在一个文档中列出，只能通过放一个链接的形式引导大家深入学习～
