### ISSUE TITLE
postMessage部分bug

### ISSUE THREAD

**Issue by lecepin** [searchfe/pwa-doc#26]
![image](https://user-images.githubusercontent.com/11046969/38137301-80212876-3456-11e8-80b2-90074aeb10b4.png)
`windowClients`对象并不能获取到。需要在clients.matchAll().then 的回调参数中使用。

https://lavas.baidu.com/pwa/engage-retain-users/notification/notification-pattern

**Comment by easonyq** [comment]
感谢指正，我们会尽快进行修改

**Comment by easonyq** [comment]
已经修改了相关部分，感谢您的反馈！
