### ISSUE TITLE
反馈：why-is-progressive.md

### ISSUE THREAD

**Issue by rxdxxxx** [searchfe/pwa-doc#27]
https://mp.weixin.qq.com/s/BiAYM-Ia5lYf0qv3DHmPjg

随着 iOS 11.3 的发布，iOS + PWA 的时代终于来了！本文对 iOS 中 PWA 的能力进行了分析，并将其与 iOS 上的 Native App、Android 上的 PWA 进行了深度对比，是值得收藏的一篇好文。

**Comment by PengXing** [comment]
嗯，这篇文章确实不错，另外，文档我已经修改了，谢谢反馈
