### ISSUE TITLE
反馈：engage-retain-users/how-push-works.md

### ISSUE THREAD

**Issue by FEjohnny** [searchfe/pwa-doc#28]
function subscribe(serviceWorkerReg) {
    serviceWorkerReg.pushManager.subscribe({ // 2. 订阅
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array('<applicationServerKey>')
    })
    .then(function (subscription) {
        // 3. 发送推送订阅对象到服务器，具体实现中发送请求到后端api
        sendEndpointInSubscription(subscription);
    })
    .catch(function () {
        if (Notification.permission === 'denied') {
            // 用户拒绝了订阅请求
        }
    });
}

这段代码，为什么我怎么操作不都能执行到【 // 3. 发送推送订阅对象到服务器】这一步，求解，谢谢！

**Comment by easonyq** [comment]
走不进第三步的 `then` 的话，有没有走进最后的 `catch` ？ 尝试在 `catch` 里面打印点信息试试看，也许是浏览器弹出了提示，你没有点允许，以后就再没机会了

**Comment by FEjohnny** [comment]
感谢回复，后来我找到解决方案了，这里订阅是需要翻墙才有效果的。如果不翻墙，就没有任何反应，也不会走到下面的流程。
