### ISSUE TITLE
反馈：offline-and-cache-loading/service-worker/service-worker-debug.md

### ISSUE THREAD

**Issue by ChinaMIC** [searchfe/pwa-doc#29]
ios11.3版本已经支持，希望可以更新一下底部安卓真机debug

**Comment by easonyq** [comment]
抱歉我没太理解您的意思。为什么前半句是 ios 11.3 已经支持，后半句是希望更新安卓的 debug 章节？能否详细描述一下？

**Comment by PengXing** [comment]
应该是想用 https 在手机上部署，有两个办法

1. 搞一个 HTTPS
2. 用代理，将手机网络代理到电脑，然后在手机上访问 localhost
